# -*- coding: utf-8 -*-
"""EDA_Masai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDYShzIvL-XkMUYUPYwtviCOhS4Z1F2o
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style='whitegrid')
plt.rcParams["figure.figsize"] = (10, 6)

# Load the data
df = pd.read_csv('/content/quotes.csv')

# Preview data
print("First 5 records:\n", df.head())
print("Last 5 records:\n", df.tail())

# Info and shape
print("\nDataset Info:")
df.info()

print("\nDataset Shape:", df.shape)

# Summary statistics
print("\nSummary Statistics:")
print(df.describe(include='all'))

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

df

# Drop duplicates
df.drop_duplicates(inplace=True)

# Drop rows with critical missing values (like title or price)
df.dropna(subset=['author', 'quote'], inplace=True)

df['tag_name'] = df['tag_name'].str.replace('-', ' ', regex=False)

# Final info check
print("\nCleaned Dataset Info:")
print(df.info())

## Data visulaization

## Most Frequent Authors (Top 10)
author_counts = df['author'].value_counts().nlargest(10)
sns.barplot(x=author_counts.values, y=author_counts.index, palette='viridis')
plt.title('Top 10 Most Quoted Authors')
plt.xlabel('Number of Quotes')
plt.ylabel('Author')
plt.tight_layout()
plt.show()

## Bar Chart – Most Common Tags (Top 10)
tag_counts = df['tag_name'].value_counts().nlargest(10)
sns.barplot(x=tag_counts.values, y=tag_counts.index, palette='mako')
plt.title('Top 10 Most Frequent Tags')
plt.xlabel('Number of Quotes')
plt.ylabel('Tag')
plt.tight_layout()
plt.show()

## Distribution of Quotes by Top 5 Authors
top_authors = df['author'].value_counts().nlargest(5)
plt.pie(top_authors.values, labels=top_authors.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('Set2'))
plt.title('Quote Distribution by Top 5 Authors')
plt.axis('equal')
plt.show()

## Quote Length Distribution
df['quote_length'] = df['quote'].apply(len)

sns.histplot(df['quote_length'], bins=30, kde=True, color='teal')
plt.title('Distribution of Quote Lengths')
plt.xlabel('Length of Quote (characters)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

## Quote Length by Author (Top 5)
top_authors = df['author'].value_counts().nlargest(5).index
subset_df = df[df['author'].isin(top_authors)]

sns.boxplot(data=subset_df, x='author', y='quote_length', palette='pastel')
plt.title('Quote Length by Top 5 Authors')
plt.xlabel('Author')
plt.ylabel('Quote Length')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()